config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'characters#new'
  resources :characters, only: [:new, :create, :destroy] do
    resource :game, only: [:show, :edit, :update], controller: 'characters/game'
  end
  resources :games, only: [:update] do
    resources :characters, only: :show, controller: 'games/characters'
  end

  resource :color, only: :show
  resource :light_setting, only: [:show, :update]

  mount ActionCable.server, at: '/cable'
end

app/models/characters/bad_guy.rb
class BadGuy < Character
  def message_for_bad_guy
    "#{name} is a bad guy."
  end

  def bad_guy?
    true
  end

  private
    def basic_knowledge
      [
        "You're a bad guy."
      ]
    end

    def special_knowledge(characters)
      messages = characters.collect(&:message_for_bad_guy).compact
      if characters.any?{|c| c.class == LiberalSpy}
        messages << "One of the bad guys is actually a good guy."
      end
      messages
    end
end

app/models/characters/character.rb
class Character < ActiveRecord::Base
  validates :name, presence: true

  after_create_commit { GameCharactersBroadcastJob.perform_now :joined, self }
  after_destroy { GameCharactersBroadcastJob.perform_now :left, self }
  after_destroy { CharacterBroadcastJob.perform_now :kicked, self }
  after_destroy :game_count_check
  after_create_commit :game_count_check

  def knowledge(characters)
    basic_knowledge + special_knowledge(characters)
  end

  def bad_guy?
    false
  end

  def message_for_bad_guy
    nil
  end

  def message_for_liberal_spy
    message_for_bad_guy
  end

  def message_for_percival
    nil
  end

  def message_for_merlin
    message_for_bad_guy
  end

  def game_count_check
    game = Game.find_by( id: self.game_id )
    if game
      game.character_count_check
    else
      0
    end
  end

  private
    def basic_knowledge
      [
        "You're a good guy."
      ]
    end

    def special_knowledge(characters)
      []
    end

end

app/models/characters/churchill.rb
class Churchill < Character
end

app/models/characters/churchill_supporter.rb
class ChurchillSupporter < Character
  private
  def special_knowledge(characters)
    if churchill = characters.find{|c| c.class == Churchill}
      return [
        "#{churchill.name} is Churchill."
      ]
    end
    []
  end
end

app/models/characters/liberal_spy.rb
class LiberalSpy < Character
  def message_for_bad_guy
    "#{name} is a bad guy."
  end

  private
    def basic_knowledge
      [
        "You're a bad guy."
      ]
    end

    def special_knowledge(characters)
      [
        "You're a spy!",
        "YOU'RE ACTUALLY A GOOD GUY.",
        "You only appear as a bad guy.",
        "You win if the good guys win."
      ] + characters.collect(&:message_for_liberal_spy).compact
    end
end

app/models/characters/merlin.rb
class Merlin < Character
  def message_for_percival
    name
  end

  private
    def special_knowledge(characters)
      [
        "You are also MERLIN",
        "Try to be helpful without giving yourself away."
      ] + characters.collect(&:message_for_merlin).compact
    end
end

app/models/characters/mordred.rb
class Mordred < BadGuy
  def message_for_merlin
    "One bad guy is unknown to you."
  end

  private
    def special_knowledge(characters)
      characters.collect(&:message_for_bad_guy).compact + [
        "You are also MORDRED.",
        "Merlin doesn't know you're bad."
      ]
    end
end

app/models/characters/morgana.rb
class Morgana < BadGuy
  def message_for_percival
    name
  end

  private
    def special_knowledge(characters)
      characters.collect(&:message_for_bad_guy).compact + [
        "You are also MORGANA.",
        "Percival thinks you might be Merlin."
      ]
    end
end

app/models/characters/oberon.rb
class Oberon < BadGuy
  def message_for_bad_guy
    "One bad guy is unknown to you."
  end

  private
    def special_knowledge(characters)
      [
        "You are also OBERON.",
        "You don't know who else is bad.",
        "Bad guys don't know you're bad."
      ]
    end
end

app/models/characters/percival.rb
class Percival < Character
  private
    def special_knowledge(characters)
      [
        "You are also PERCIVAL",
        "Try to be supportive of Merlin without exposing him.",
        "One of the following players is Merlin:"
      ] + characters.collect(&:message_for_percival).compact
    end
end

app/models/characters/secret_hitler.rb
class SecretHitler < BadGuy
  def message_for_bad_guy
    "#{name} is Secret Hitler."
  end

  def message_for_liberal_spy
    "#{name} is a bad guy."
  end

  private
    def basic_knowledge
      [
        "You're a bad guy."
      ]
    end

    def special_knowledge(characters)
      messages = [
        "You're also Secret Hitler."
      ]

      number_of_bad_guys = characters.count(&:bad_guy?)
      if number_of_bad_guys > 1
        messages + [
          "There are #{number_of_bad_guys} other bad guys.",
          "They know who you are."
        ]
      else
        messages + characters.collect(&:message_for_bad_guy).compact
      end
    end
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :characters
  belongs_to :owner, class_name: "Character"
  validates_presence_of :bad_number

  after_update { GameBroadcastJob.perform_now :updated, self }

  def self.default_scope
    where(arel_table[:created_at].gt(DateTime.now - 1.day))
  end

  def self.build
    create(code: new_code)
  end

  def special_character_hash
    {
      special_good: special_good,
      special_bad: special_bad,
      bad_number: bad_number
    }.compact
  end

  def character_count_check
    GameBroadcastJob.perform_now :updated, self
  end

  def is_owner? character
    self.owner == character
  end

  def has_owner?
    self.owner != nil
  end

  def is_ready?
    self.characters.length > 4
  end

  private
    def self.new_code
      letters = ('a'..'z').to_a
      allowed_code = nil
      loop do
        allowed_code = "#{letters.sample}#{letters.sample}#{letters.sample}#{letters.sample}"
        unless where(code: allowed_code).present?
          break
        end
      end
      allowed_code
    end
end

app/controllers/characters/game_controller.rb
module Characters
  class GameController < ApplicationController
    before_action :get_character

    def edit
      @game = Game.find @character.game_id
    end

    def update
      @game = Game.find @character.game_id
      @game.update(
        bad_number: game_params[:bad_number],
        special_good: game_params.fetch(:special_good, []),
        special_bad: game_params.fetch(:special_bad, [])
      )
      if @game.errors.blank?
        flash[:notice] = "Game Updated!"
      else
        flash[:notice] = @game.errors.full_messages
      end
      redirect_to :back
    end

    def show
      @game = Game.includes(:characters).find @character.game_id
      redirect_to game_character_path(@game, @character) if @game.active
    end

    private
    def get_character
      @character = ::Character.find params[:character_id]
    end

    def game_params
      params.require(:game).permit(
        :bad_number, special_bad: [], special_good: []
      )
    end
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    check_for_game

    # return if unable to join
    render :new and return if cant_join?

    @character.game_id = game.id # need this so that game is set when cabled to client
    if @character.save
      # if game host is not set, then set it
      unless game.has_owner?
        game.owner_id = @character.id
        game.save
      end

      game.characters << @character

      redirect_to character_game_path @character
    else
      render :new
    end
  end

  def destroy
    character = Character.find_by id: params[:id]
    character.destroy if character.present?
    redirect_to :back
  end

  private
  def check_for_game
    @game = Game.where(code: game_params[:code].downcase.strip).first
  end

  def cant_join?
    if @game.blank? && game_params[:code].present?
      flash[:notice] = "Game with code #{game_params[:code]} does not exist."
      true
    elsif @game.present? && @game.active
      flash[:notice] = "Game with code #{game_params[:code]} started without you."
      true
    elsif @game.present? && @game.characters.count == 15
      flash[:notice] = "Game with code #{game_params[:code]} is full."
      true
    else
      false
    end
  end

  def game
    @game ||= Game.build
  end

  def character_params
    params.require(:character).permit(:name)
  end

  def game_params
    params.require(:game).permit(:code)
  end
end

app/controllers/games/characters_controller.rb
module Games
  class CharactersController < ApplicationController
    before_action :get_game

    def show
      @character = Character.find params[:id]
      redirect_to character_game_path(@character) unless @game.active
      characters = @game.characters - [@character]
      @knowledge = @character.knowledge(characters)
    end

    private
    def get_game
      @game = Game.includes(:characters).find params[:game_id]
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def update
    @game = Game.find params[:id]
    @game.update(game_params)
    ::GameBuilder.new(@game).assign_random_roles(@game.special_character_hash)
    redirect_to :back
  end

  private
  def game_params
    params.require(:game).permit(:active)
  end
end

app/views/characters/game/_bad_chars.html.erb
<% if game.special_bad.present? %><p>Special Bad Characters: <%= game.special_bad.join(", ") %></p><% end %>

app/views/characters/game/_character.html.erb
<li data-character="<%=character.id%>" style="overflow-wrap: break-word;"><!--
  --><%= "#{character.name}" %><!--
  <% if character == yourself %>
   -->&nbsp;(you)<!--
  <% elsif game.is_owner? character %>
   -->&nbsp;(host)<!--
  <% elsif game.is_owner? yourself %>
   -->&nbsp;<a class="character-remove">Remove</a><!--
  <% end %>
--></li>

app/views/characters/game/_good_chars.html.erb
<% if game.special_good.present? %><p>Special Good Characters: <%= game.special_good.join(", ") %></p><% end %>

app/views/characters/game/_start.html.erb
<div id="game-not-ready" <% if game.is_ready? %>style="display:none;"<% end %>>
  <span class="label primary">Waiting for more characters to join</span>
</div>
<div id="game-ready" <% if ! game.is_ready? %>style="display:none;"<% end %>>
  <% if game.is_owner? character %>
    <button type="submit" class="button success">Start Game</button>
  <% else %>
    <span# class="label success">Waiting for host to start</span>
  <% end %>
</div>

app/views/characters/game/edit.html.erb
<div class="cell">
  <%= form_for @game, url: character_game_path  do |f| %>
    <% if @game.errors.present? || flash[:notice].present? %>
        <div id="error_explanation">
          <ul>
            <% [*@game.errors.full_messages, *flash[:notice]].each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <p>
      <%= f.label "Number of Bad Characters" %><br>
      <%= f.text_field :bad_number %>
    </p>
    <h4>Special Good Characters</h4>
    <%= check_box_tag "game[special_good][]", "Merlin", @game.special_good.include?("Merlin") %>
    <%= f.label "Merlin (knows evil, must remain hidden)" %></br>
    <%= check_box_tag "game[special_good][]", "Percival", @game.special_good.include?("Percival") %>
    <%= f.label "Percival (knows Merlin)" %></br>
    <%= check_box_tag "game[special_good][]", "LiberalSpy", @game.special_good.include?("LiberalSpy") %>
    <%= f.label "Liberal Spy (appears bad)" %></br>
    <%= check_box_tag "game[special_good][]", "Churchill", @game.special_good.include?("Churchill") %>
    <%= f.label "Churchill" %></br>
    <%= check_box_tag "game[special_good][]", "ChurchillSupporter", @game.special_good.include?("ChurchillSupporter") %>
    <%= f.label "Churchill Supporter (knows who Churchill is)" %>
    <h4>Special Bad Characters</h4>
    <%= check_box_tag "game[special_bad][]", "Mordred", (@game.special_bad || []).include?("Mordred") %>
    <%= f.label "Mordred (unknown to Merlin)" %></br>
    <%= check_box_tag "game[special_bad][]", "Morgana", (@game.special_bad || []).include?("Morgana") %>
    <%= f.label "Morgana (appears as Merlin)" %></br>
    <%= check_box_tag "game[special_bad][]", "Oberon", (@game.special_bad || []).include?("Oberon") %>
    <%= f.label "Oberon (unknown to evil)" %></br>
    <%= check_box_tag "game[special_bad][]", "SecretHitler", (@game.special_bad || []).include?("SecretHitler") %>
    <%= f.label "Secret Hitler" %>
    <div class="button-group">
      <%= f.submit "Update", class: "button warning" %><%= link_to "Back To Game", character_game_path, class: "button" %>
    </div>
  <% end %>
</div>

app/views/characters/game/show.html.erb
<div class="cell">
  <h3>Game Code: <span class="label" style="font-size:1.2em;"><%= @game.code%></span></h3>

  <% if @game.is_owner? @character %>
    <%= link_to "Configure", edit_character_game_path, class: 'button' %>
  <% end %>

  <div id="game-bad-chars"><%= render partial: "bad_chars", locals: { game: @game } %></div>
  <div id="game-good-chars"><%= render partial: "good_chars", locals: { game: @game } %></div>
  <p>
    Number of Bad Characters: <span class="label alert" id="game-bad-number"><%= @game.bad_number %></span>
  </p>

  People who have joined (currently <span id="character-count"><%= @game.characters.count %></span>):
  <ul id="character-list" data-game="<%=@game.id%>" >
    <% @game.characters.each do |character| %>
      <%= render partial: "character", locals: { character: character, yourself: @character, game: @game } %>
    <% end %>
  </ul>

  <%= form_for @game do |f| %>
    <%= f.hidden_field :active, value: '1' %>
    <div id="game-start"><%= render partial: "start", locals: { game: @game, character: @character } %></div>
  <% end %>
</div>



<script>
  const game = <%= @game.to_json.html_safe %>;
  const character = <%= @character.to_json.html_safe %>;

  // app/assets/javascript/channels/game.coffee
  if( typeof activateGameChannel == "function" ) { App["game"] = activateGameChannel( game ); }
  // app/assets/javascript/channels/character.coffee
  if( typeof activateCharacterChannel == "function" ) { App["character"] = activateCharacterChannel( character ); }
  // app/assets/javascript/channels/game_character.coffee
  if( typeof activateGameCharactersChannel == "function" ) { App["gameCharacters"] = activateGameCharactersChannel( game ); }


  $(document).on('turbolinks:load', function() {
    $("#character-list").on('click', '.character-remove', function(event) {
      $target = $(event.currentTarget);

      App["gameCharacters"].send({
        characterId: $target.parents('li').data().character,
        action: "kick"
      });

      event.preventDefault();
    });
  });
</script>